/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package sg.com.para.intranet.expense.services.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Expense service. Represents a row in the &quot;intranet_expense&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link sg.com.para.intranet.expense.services.model.impl.ExpenseModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link sg.com.para.intranet.expense.services.model.impl.ExpenseImpl}.
 * </p>
 *
 * @author Fernando Karnagi
 * @see Expense
 * @see sg.com.para.intranet.expense.services.model.impl.ExpenseImpl
 * @see sg.com.para.intranet.expense.services.model.impl.ExpenseModelImpl
 * @generated
 */
public interface ExpenseModel extends BaseModel<Expense> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a expense model instance should use the {@link Expense} interface instead.
	 */

	/**
	 * Returns the primary key of this expense.
	 *
	 * @return the primary key of this expense
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this expense.
	 *
	 * @param primaryKey the primary key of this expense
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the expense ID of this expense.
	 *
	 * @return the expense ID of this expense
	 */
	public int getExpenseId();

	/**
	 * Sets the expense ID of this expense.
	 *
	 * @param expenseId the expense ID of this expense
	 */
	public void setExpenseId(int expenseId);

	/**
	 * Returns the employee screen name of this expense.
	 *
	 * @return the employee screen name of this expense
	 */
	@AutoEscape
	public String getEmployeeScreenName();

	/**
	 * Sets the employee screen name of this expense.
	 *
	 * @param employeeScreenName the employee screen name of this expense
	 */
	public void setEmployeeScreenName(String employeeScreenName);

	/**
	 * Returns the log date of this expense.
	 *
	 * @return the log date of this expense
	 */
	public Date getLogDate();

	/**
	 * Sets the log date of this expense.
	 *
	 * @param logDate the log date of this expense
	 */
	public void setLogDate(Date logDate);

	/**
	 * Returns the amount of this expense.
	 *
	 * @return the amount of this expense
	 */
	public double getAmount();

	/**
	 * Sets the amount of this expense.
	 *
	 * @param amount the amount of this expense
	 */
	public void setAmount(double amount);

	/**
	 * Returns the remarks of this expense.
	 *
	 * @return the remarks of this expense
	 */
	@AutoEscape
	public String getRemarks();

	/**
	 * Sets the remarks of this expense.
	 *
	 * @param remarks the remarks of this expense
	 */
	public void setRemarks(String remarks);

	/**
	 * Returns the status of this expense.
	 *
	 * @return the status of this expense
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this expense.
	 *
	 * @param status the status of this expense
	 */
	public void setStatus(String status);

	/**
	 * Returns the project code of this expense.
	 *
	 * @return the project code of this expense
	 */
	@AutoEscape
	public String getProjectCode();

	/**
	 * Sets the project code of this expense.
	 *
	 * @param projectCode the project code of this expense
	 */
	public void setProjectCode(String projectCode);

	/**
	 * Returns the approved by of this expense.
	 *
	 * @return the approved by of this expense
	 */
	@AutoEscape
	public String getApprovedBy();

	/**
	 * Sets the approved by of this expense.
	 *
	 * @param approvedBy the approved by of this expense
	 */
	public void setApprovedBy(String approvedBy);

	/**
	 * Returns the approved date of this expense.
	 *
	 * @return the approved date of this expense
	 */
	public Date getApprovedDate();

	/**
	 * Sets the approved date of this expense.
	 *
	 * @param approvedDate the approved date of this expense
	 */
	public void setApprovedDate(Date approvedDate);

	/**
	 * Returns the processed by of this expense.
	 *
	 * @return the processed by of this expense
	 */
	@AutoEscape
	public String getProcessedBy();

	/**
	 * Sets the processed by of this expense.
	 *
	 * @param processedBy the processed by of this expense
	 */
	public void setProcessedBy(String processedBy);

	/**
	 * Returns the processed date of this expense.
	 *
	 * @return the processed date of this expense
	 */
	public Date getProcessedDate();

	/**
	 * Sets the processed date of this expense.
	 *
	 * @param processedDate the processed date of this expense
	 */
	public void setProcessedDate(Date processedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		sg.com.para.intranet.expense.services.model.Expense expense);

	@Override
	public int hashCode();

	@Override
	public CacheModel<sg.com.para.intranet.expense.services.model.Expense> toCacheModel();

	@Override
	public sg.com.para.intranet.expense.services.model.Expense toEscapedModel();

	@Override
	public sg.com.para.intranet.expense.services.model.Expense toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}